exports.appString = {
    USERNAME_REQUIRED: "Username is required",
    EMAILALREDYREGISTERED: "Email already registered",
    USERREGISTRATIONSUCCESSFULL: "Registration successful. Please verify your email",
    SERVERERROR: "Server Error",
    INVALIDEXPIREDLINK: "Invalid or Expired Link",
    CATEGORYSUCCESS: "Category Added Successfully",
    SUBCATEGORYSUCCESS: "SubCategory Added Successfully",
    PARENTCATEGORY: "Parent Category Not Found ",
    SUBCATEGORYNOTFOUND: "subCategory Not Found",
    CATEGORYNOTFOUND: "Category Not Found",
    CATEGORYFECTH: "Category Fetched Successfully",
    QUIZCREATEDSUCCESS: "Quiz Created Successfully",
    QUIZUPDATED: "Quiz Updated SuccessFully",
    QUIZNOTFOUND:"Quiz Not Found ",
    QUESTIONCREATED:"Question Created Succesfully",
    QUIZQUESTIONLIMIT: "This quiz already has the maximum of 10 questions.",
    OPTIONWITHARRAYLIMITWITH4:"Options should be an array with at least 4 items.",
    ONEOPTIONCORRECT: "You must mark exactly one option as correct.",
    MULTIPLECOORECTANSWERNOTALLOWED: "Multiple correct answers are not allowed. Only one 'isCorrect: 1' allowed.",
    TEXTASSTRINGISCOORECTASNUMBER:"Each option should have 'text' as string and 'isCorrect' as Number.",
    QUESTIONNOTFOUND:"Question Not Found",
    QUESTIONUPDATED:"Question updated successfully",
    INVALIDDIFFICULTYLEVEL:"Invalid difficulty level",
    WITHDRAWREQUESTSUBMITED:"withdraw request Submitted",
    INSUFFICIANTPOINTS:"Insufficiant Points "
};
