exports.appString = {
    USERNAME_REQUIRED: "Username is required",
    EMAILALREDYREGISTERED: "Email already registered",
    USERREGISTRATIONSUCCESSFULL: "Registration successful. Please verify your email",
    SERVERERROR: "Server Error",
    EMAIL_REQUIRED:"Email Is Required",
    INVALIDEXPIREDLINK: "Invalid or Expired Link",
    CATEGORYSUCCESS: "Category Added Successfully",
    SUBCATEGORYSUCCESS: "SubCategory Added Successfully",
    PARENTCATEGORY: "Parent Category Not Found ",
    SUBCATEGORYNOTFOUND: "subCategory Not Found",
    CATEGORYNOTFOUND: "Category Not Found",
    CATEGORYFECTH: "Category Fetched Successfully",
    QUIZCREATEDSUCCESS: "Quiz Created Successfully",
    QUIZUPDATED: "Quiz Updated SuccessFully",
    QUIZNOTFOUND: "Quiz Not Found ",
    QUESTIONCREATED: "Question Created Succesfully",
    QUIZQUESTIONLIMIT: "This quiz already has the maximum of 10 questions.",
    OPTIONWITHARRAYLIMITWITH4: "Options should be an array with at least 4 items.",
    ONEOPTIONCORRECT: "You must mark exactly one option as correct.",
    MULTIPLECOORECTANSWERNOTALLOWED: "Multiple correct answers are not allowed. Only one 'isCorrect: 1' allowed.",
    TEXTASSTRINGISCOORECTASNUMBER: "Each option should have 'text' as string and 'isCorrect' as Number.",
    QUESTIONNOTFOUND: "Question Not Found",
    QUESTIONUPDATED: "Question updated successfully",
    INVALIDDIFFICULTYLEVEL: "Invalid difficulty level",
    WITHDRAWREQUESTSUBMITED: "withdraw request Submitted",
    INSUFFICIANTPOINTS: "Insufficiant Points ",
    REQUESTNOTFOUND: "Request Not Found",
    REQUESTALREDYPROCEED: "Request already processed",
    WITHDRAWREQUESTREJECTED: "Withdraw request rejected",
    WITHDRAWAPPROVED: "Withdraw approved",
    USERBANNEDSUCCESS: "User banned successfully",
    USERUNBANEDNOTSUCCESS: "User unbanned successfully",
    USERREGISTRATIONSUCCESSFULLVERIFIED: "You Are Verfied And Registered Is Complete",
    INVALID_CREDENTIALS: "Invalid Login Credential",
    CHECKVERIFYLOGIN: "Please check your email to verify login.",
    LOGINSUCCESS:"Login Successful",
    LOGIN_FAILED:"Login Failed",
    LOGOUT_SUCCESS:"Logout Successfully",
    LOGOUT_FAILED:"LogOut Failed",
    USERNOTFOUND:"User Not Found",
    LOGIN_SUCCESS:"Login Successfully",
    INVALIDPASSWORD:"Invalid Password",
    LOGINFIRSTFROMMAIL:"Please verify your login first from email",
    VERIFICATIONMAILSEND:"Verification email sent. Please check your Email.",
    LOGINFAILED:"Login Failed",
    LOGINVERIFICATIONSUCCESSFULL:"Yours Login Verification Succesfull",
    QUIZCOMPLETE: "Quiz completed",
     TIMETAKENREQUIREDFORLAST:"timeTaken required for last question",
     ANSWERSUBMITTED:"Answer Submitted Successfully",
     ALREDYATTEMPTEDQUESTION:"You already attempted this question"
};
